### 1
POST http://localhost:3008/login
Content-Type: application/json

{
    "username": "german",
    "password": "Hola"
}
###1.Obtener todos los productos (RUTA PROTEGIDA)
GET http://localhost:3008/productos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw

###2. Obtener un producto por ID (RUTA PROTEGIDA)
GET http://localhost:3008/productos/6677484a73a84c49299bb3d5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw


###2b. Obtener un producto por Codigo (RUTA PROTEGIDA)
GET http://localhost:3008/productos/1234
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw

###3. Filtrar un producto por nombre
GET http://localhost:3008/productos/nombre/Detergente
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw

###4. Agregar un producto
POST http://localhost:3008/productos/
content-type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw

{
    "nombre": "Azufre",
    "precio": 35.50,
    "categoria": "Limpieza"
}
###5. Modificar/Actualizar un precio
PATCH http://localhost:3008/productos/6677484a73a84c49299bb3d5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw
content-type: application/json

{
    "precio": 200000
}

###6. Borrar un producto por id
DELETE http://localhost:3008/productos/6677484a73a84c49299bb3d5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlcm1hbiIsImlhdCI6MTcxOTQ5NzcyNSwiZXhwIjoxNzE5NTAxMzI1fQ.xPXV_hSFhn5dg_ewJRQ6SAlNj17fPzeoqJzUKl-qeLw
